
inherit_from: configs/learning_based/outlier/ours_7x.yaml
data:
  class: ['']
  path: input/bench
train:
  out_dir: out/input/outlier/bench
test:
  model_file: https://s3.eu-central-1.amazonaws.com/avg-projects/shape_as_points/models/ours_outlier_7x.pt